### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by hathix** [Harvard-Open-Data-Project/hodp#13]
[Demo Dataverse](https://dataverse-demo.iq.harvard.edu/)

**Comment by nsinai** [comment]
Datamade just released their ETL workflow: https://github.com/datamade/data-making-guidelines  

What's ETL? ETL stands for extract, transfer and load. Simply, it's the process of moving and reformatting structured data between 2 locations.  

What resources and tools exist? Code for America has gathered some here: https://github.com/codeforamerica/etl-for-america/wiki 

ETL for America is a great 101 post if you have not read it before: http://daguar.github.io/2014/03/17/etl-for-america/

**Comment by nsinai** [comment]
OpenRefine --> CKAN tool from Ontodia. 

https://github.com/Ontodia/openrefine-ckan-storage-extension
